import { motion } from 'framer-motion'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { login, register } from '../config/api'
import { useApp } from '../context/AppContext'
import './SignUp.css'

const SignUp = () => {
  const navigate = useNavigate()
  const { setIsAuthenticated, setUserProfile } = useApp()

  const [currentStep, setCurrentStep] = useState(1)
  const [formData, setFormData] = useState({
    fullName: '',
    dateOfBirth: '',
    email: '',
    password: '',
    confirmPassword: '',
    state: '',
    city: '',
    pincode: '',
    role: '',
    employeeId: '',
    freelancerId: ''
  })

  const [errors, setErrors] = useState({})
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)

  const indianStates = [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
    'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
    'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
    'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
    'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
    'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
    'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep', 'Puducherry'
  ]

  const validateEmail = (email) => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    return emailRegex.test(email)
  }

  const validatePassword = (password) => {
    const minLength = password.length >= 8
    const hasUpperCase = /[A-Z]/.test(password)
    const hasNumber = /[0-9]/.test(password)
    const hasSpecialChar = /[!@#$%^&*(),.?":{}|<>]/.test(password)

    return {
      valid: minLength && hasUpperCase && hasNumber && hasSpecialChar,
      errors: {
        minLength: !minLength ? 'Password must be at least 8 characters' : '',
        hasUpperCase: !hasUpperCase ? 'Password must contain at least 1 uppercase letter' : '',
        hasNumber: !hasNumber ? 'Password must contain at least 1 number' : '',
        hasSpecialChar: !hasSpecialChar ? 'Password must contain at least 1 special character' : ''
      }
    }
  }

  const validatePincode = (pincode) => {
    const pincodeRegex = /^\d{6}$/
    return pincodeRegex.test(pincode)
  }

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: value,
      ...(name === 'role' && {
        employeeId: '',
        freelancerId: ''
      })
    }))

    if (errors[name]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }))
    }
  }

  const validateField = (name, value) => {
    let error = ''
    switch (name) {
      case 'fullName':
        if (!value.trim()) error = 'Full name is required'
        break
      case 'dateOfBirth':
        if (!value) error = 'Date of birth is required'
        break
      case 'email':
        if (!value) {
          error = 'Email address is required'
        } else if (!validateEmail(value)) {
          error = 'Please enter a valid email address'
        }
        break
      case 'password':
        if (!value) {
          error = 'Password is required'
        } else {
          const passwordValidation = validatePassword(value)
          if (!passwordValidation.valid) {
            error = Object.values(passwordValidation.errors).filter(e => e).join(', ')
          }
        }
        break
      case 'confirmPassword':
        if (!value) {
          error = 'Please confirm your password'
        } else if (value !== formData.password) {
          error = 'Passwords do not match'
        }
        break
      case 'state':
        if (!value) error = 'Please select your state'
        break
      case 'city':
        if (!value.trim()) error = 'City is required'
        break
      case 'pincode':
        if (!value) {
          error = 'Pincode is required'
        } else if (!validatePincode(value)) {
          error = 'Pincode must be exactly 6 digits'
        }
        break
      case 'role':
        if (!value) error = 'Role is required'
        break
      case 'employeeId':
        if (formData.role === 'Company Employee' && !value.trim()) {
          error = 'Employee ID is required'
        }
        break
      case 'freelancerId':
        // Freelancer ID is auto-generated by backend, no validation needed
        break
      default:
        break
    }
    return error
  }

  const isStepValid = (step) => {
    const stepFields = {
      1: ['fullName', 'email', 'password', 'confirmPassword'],
      2: ['role', ...(formData.role === 'Company Employee' ? ['employeeId'] : [])],  // Freelancer ID is auto-generated
      3: ['dateOfBirth', 'state', 'city', 'pincode']
    }

    const currentFields = stepFields[step]
    let isValid = true
    const newErrors = { ...errors }

    currentFields.forEach(field => {
      const error = validateField(field, formData[field])
      if (error) {
        newErrors[field] = error
        isValid = false
      }
    })

    setErrors(newErrors)
    return isValid
  }

  const handleNext = (e) => {
    e.preventDefault()
    if (isStepValid(currentStep)) {
      setCurrentStep(prev => prev + 1)
    }
  }

  const handleBack = () => {
    setCurrentStep(prev => prev - 1)
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!isStepValid(3)) return

    setIsSubmitting(true)
    try {
      const signupData = {
        name: formData.fullName,
        email: formData.email,
        password: formData.password,
        dob: formData.dateOfBirth,
        state: formData.state,
        city: formData.city,
        pincode: formData.pincode,
        employment_type: formData.role,  // Backend expects 'employment_type', not 'role'
        employee_id: formData.employeeId,
        freelancer_id: formData.freelancerId,
        mode: 'user'
      }

      await register(signupData)
      // After successful signup, redirect to login page
      setIsSubmitting(false)
      navigate('/login', {
        state: { message: 'Account created successfully! Please login to continue.' }
      })
    } catch (error) {
      setErrors({ submit: error.message || 'Signup failed. Please try again.' })
      setIsSubmitting(false)
    }
  }

  const handleBlur = (e) => {
    const { name, value } = e.target
    const error = validateField(name, value)
    if (error) {
      setErrors(prev => ({ ...prev, [name]: error }))
    }
  }

  const steps = [
    { number: 1, label: 'Identity' },
    { number: 2, label: 'Professional' },
    { number: 3, label: 'Location' }
  ]

  return (
    <div className="signup-container">
      <motion.div
        className="auth-page-wrapper"
        initial={{ rotateY: 180, opacity: 0 }}
        animate={{ rotateY: 0, opacity: 1 }}
        exit={{ rotateY: -180, opacity: 0 }}
        transition={{ duration: 0.8, ease: "easeInOut" }}
      >
        <div className="signup-card">
          <motion.div
            className="brand-header"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            <h1 className="brand-title">Techbank.Ai</h1>
            <p className="brand-tagline">Join our Enterprise Platform</p>
          </motion.div>

          <div className="steps-container">
            {steps.map((step) => (
              <div
                key={step.number}
                className={`step-item ${currentStep === step.number ? 'active' : ''} ${currentStep > step.number ? 'completed' : ''}`}
              >
                <div className="step-number">{step.number}</div>
                <div className="step-label">{step.label}</div>
              </div>
            ))}
          </div>

          <form autoComplete="off" onSubmit={currentStep === 3 ? handleSubmit : handleNext} className="signup-form">
            {currentStep === 1 && (
              <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                className="step-content"
              >
                <div className="form-group">
                  <label htmlFor="fullName">Full Name</label>
                  <input
                    type="text"
                    id="fullName"
                    name="fullName"
                    value={formData.fullName}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    placeholder="Enter your full name"
                    className={errors.fullName ? 'error' : ''}
                  />
                  {errors.fullName && <span className="error-message">{errors.fullName}</span>}
                </div>

                <div className="form-group">
                  <label htmlFor="email">Email Address</label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    placeholder="name@example.com"
                    className={errors.email ? 'error' : ''}
                    autoComplete="none"
                  />
                  {errors.email && <span className="error-message">{errors.email}</span>}
                </div>

                <div className="form-row">
                  <div className="form-group">
                    <label htmlFor="password">Password</label>
                    <div className="password-input-wrapper">
                      <input
                        type={showPassword ? 'text' : 'password'}
                        id="password"
                        name="password"
                        value={formData.password}
                        onChange={handleChange}
                        onBlur={handleBlur}
                        placeholder="••••••••"
                        className={errors.password ? 'error' : ''}
                        autoComplete="new-password"
                      />
                      <button
                        type="button"
                        className="password-toggle"
                        onClick={() => setShowPassword(!showPassword)}
                      >
                        {showPassword ? '👁️' : '🙈'}
                      </button>
                    </div>
                  </div>
                  <div className="form-group">
                    <label htmlFor="confirmPassword">Confirm</label>
                    <div className="password-input-wrapper">
                      <input
                        type={showConfirmPassword ? 'text' : 'password'}
                        id="confirmPassword"
                        name="confirmPassword"
                        value={formData.confirmPassword}
                        onChange={handleChange}
                        onBlur={handleBlur}
                        placeholder="••••••••"
                        className={errors.confirmPassword ? 'error' : ''}
                        autoComplete="new-password"
                      />
                      <button
                        type="button"
                        className="password-toggle"
                        onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                      >
                        {showConfirmPassword ? '👁️' : '🙈'}
                      </button>
                    </div>
                  </div>
                </div>
                {(errors.password || errors.confirmPassword) && (
                  <span className="error-message">{errors.password || errors.confirmPassword}</span>
                )}
              </motion.div>
            )}

            {currentStep === 2 && (
              <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                className="step-content"
              >
                <div className="form-group">
                  <label htmlFor="role">Your Role</label>
                  <select
                    id="role"
                    name="role"
                    value={formData.role}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    className={errors.role ? 'error' : ''}
                  >
                    <option value="">Select Your Role</option>
                    <option value="Company Employee">Company Employee</option>
                    <option value="Freelancer">Freelancer</option>
                    <option value="Guest User">Guest User</option>
                  </select>
                  {errors.role && <span className="error-message">{errors.role}</span>}
                </div>

                {formData.role === 'Company Employee' && (
                  <div className="form-group">
                    <label htmlFor="employeeId">Employee ID</label>
                    <input
                      type="text"
                      id="employeeId"
                      name="employeeId"
                      value={formData.employeeId}
                      onChange={handleChange}
                      onBlur={handleBlur}
                      placeholder="CT1001"
                      className={errors.employeeId ? 'error' : ''}
                    />
                    <small className="field-hint">Enter your company-assigned Employee ID (e.g., CT1001)</small>
                    {errors.employeeId && <span className="error-message">{errors.employeeId}</span>}
                  </div>
                )}

                {formData.role === 'Freelancer' && (
                  <div className="form-group">
                    <label>Freelancer ID</label>
                    <div className="auto-generated-notice">
                      <span className="auto-icon">🔐</span>
                      <span>Your unique Freelancer ID will be automatically generated upon registration</span>
                    </div>
                  </div>
                )}
              </motion.div>
            )}

            {currentStep === 3 && (
              <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                className="step-content"
              >
                <div className="form-group">
                  <label htmlFor="dateOfBirth">Date of Birth</label>
                  <input
                    type="date"
                    id="dateOfBirth"
                    name="dateOfBirth"
                    value={formData.dateOfBirth}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    className={errors.dateOfBirth ? 'error' : ''}
                  />
                  {errors.dateOfBirth && <span className="error-message">{errors.dateOfBirth}</span>}
                </div>

                <div className="form-row">
                  <div className="form-group">
                    <label htmlFor="state">State</label>
                    <select
                      id="state"
                      name="state"
                      value={formData.state}
                      onChange={handleChange}
                      className={errors.state ? 'error' : ''}
                    >
                      <option value="">Select State</option>
                      {indianStates.map(s => <option key={s} value={s}>{s}</option>)}
                    </select>
                  </div>
                  <div className="form-group">
                    <label htmlFor="pincode">Pincode</label>
                    <input
                      type="text"
                      id="pincode"
                      name="pincode"
                      value={formData.pincode}
                      onChange={handleChange}
                      placeholder="110001"
                      className={errors.pincode ? 'error' : ''}
                    />
                  </div>
                </div>

                <div className="form-group">
                  <label htmlFor="city">City</label>
                  <input
                    type="text"
                    id="city"
                    name="city"
                    value={formData.city}
                    onChange={handleChange}
                    placeholder="New Delhi"
                    className={errors.city ? 'error' : ''}
                  />
                  {errors.city && <span className="error-message">{errors.city}</span>}
                </div>
              </motion.div>
            )}

            {errors.submit && <div className="error-message" style={{ textAlign: 'center' }}>{errors.submit}</div>}

            <div className="form-actions">
              {currentStep > 1 && (
                <button type="button" className="back-button" onClick={handleBack}>
                  Back
                </button>
              )}
              <button
                type="submit"
                className="signup-button continue-button"
                disabled={isSubmitting}
              >
                {isSubmitting ? 'Registering...' : currentStep === 3 ? 'Complete Registration' : 'Continue'}
              </button>
            </div>

            <div className="signup-footer">
              <p>
                Already have an account?{' '}
                <Link to="/login" className="signup-link">Sign in</Link>
              </p>
            </div>
          </form>
        </div>
      </motion.div>
    </div>
  )
}

export default SignUp

